### ISSUE TITLE
Help for use the Managed Identity system

### ISSUE THREAD

**Issue by theoricher** [tomasrudh/AutoShutdownSchedule#21]
Hello,

Thank you for this very practical script. 
I want to use the Managed Identity system but I am getting the following error.

![image](https://user-images.githubusercontent.com/12476264/225742096-10e2fc32-b4f9-40e6-9cad-ee0f13e6bf87.png)

I think he can't do this step:

```
    $ManagedIdentityId = Get-AutomationVariable -Name "Managed Identity ID" -ErrorAction Ignore
    $RunAsConnection = Get-AutomationConnection -Name "AzureRunAsConnection" -ErrorAction Ignore
    if ($ManagedIdentityId -eq 'System') {
        Write-Output ("Logging in to Azure using the system managed identity...")
        if ($AzureSubscriptionName.Length -eq 0) {
            throw "No subscription indicated"
        }
        Connect-AzAccount -Identity -Subscription $AzureSubscriptionName -EnvironmentName $AzureEnvironmentName > $null
    }
```

What do I need to do to make the Managed Identity ID work?

Thank you for your help

**Comment by theoricher** [comment]
Hello,
I just realised, I must have been tired. 😄 
For people like me who did not understand, here is what to do:
1) Go to Variables (at the automation account level)
2) Add a variable (Default Azure Subscription) which contains the name of your Subscription (Ex : Azure subscription 1)
3) Add a variable (Managed Identity ID) which contains the "Object ID" (retrievable in the identity tab) 

You can encrypt the variables and the script works too!

![image](https://user-images.githubusercontent.com/12476264/225999393-d41523ad-ff9d-4fd3-8677-829fc46a0dfd.png)

![image](https://user-images.githubusercontent.com/12476264/226000029-b11acdbe-c27b-428a-9332-19c42c7edce9.png)

Thanks @tomasrudh for this script !

**Comment by tomasrudh** [comment]
Thanks for reporting, and solving it yourself!

As an addition, when you use a System Managed Identity can you set the variable 'Managed Identity ID' to the word 'System'.

/Tomas
