### ISSUE TITLE
AutoShutdownSchedule tag issue

### ISSUE THREAD

**Issue by bskurski** [tomasrudh/AutoShutdownSchedule#23]
Running into an issue with my tags not working. I am getting a Invalid tag message but cannot figure out what the issue is. I have tried multiple formats. Below is the tag I am using and the error message.

AutoShutdownSchedule : 7 PM -> 7 AM, Saturday, Sunday
Invalid tag: '7 PM -> 6 AM, Saturday, Sunday'. Skipping this VM

**Comment by tomasrudh** [comment]
Hi, thanks for reporting!

Try to remove the spaces in your tags. There is already an enhancement request to make the script tolerant to spaces.

/Tomas

**Comment by bskurski** [comment]
That worked thanks for the quick response.

Brian Skurski
Infrastructure Engineer
PORT OF TACOMA
O: 253.428.8641 | C: 253.495.2897
www.portoftacoma.com<../../../../../cbua/AppData/Local/aoda/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/LFFA90JQ/www.portoftacoma.com>
