### ISSUE TITLE
More Flexible Parsing of TimeZone

### ISSUE THREAD

**Issue by margani** [tomasrudh/AutoShutdownSchedule#25]
**Is your feature request related to a problem? Please describe.**
I am limited to enter Time Zone with it's Id.

**Describe the solution you'd like**
We could make it more flexible and accept UTC offsets, like UTC+3, etc.

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
-

**Comment by tomasrudh** [comment]
Hello and thanks for the suggestion. I understand your idea but it has a major drawback, it does not consider daylight saving time. For example, if you use CET, the time will get automatically adjusted for daylight saving time, where UTC+1 will not.

**Comment by margani** [comment]
Hi, and thank you for this wonderful script, although I have found it only recently.

I thought it's simply changing [this line](https://github.com/tomasrudh/AutoShutdownSchedule/blob/5d00f0d05c4fd0ec37acc66101b651e4c219e3ed/AutoShutdownSchedule.ps1#L94) to be more flexible than accepting only the Id of the time zone. How can that affect the daylight saving?

**Comment by margani** [comment]
Actually I just realised that you are right, it does affect that, which totally makes sense. 

Our use case was that we wanted to shutdown the VM on the weekend only until Sunday 9pm, not at midnight. And because the expression doesn't support this, we were looking for UTC+3, so its midnight matches 9pm our time.

I guess it's better to work on the expression instead, so it's more flexible. Do you agree with the suggestion to accept "12am -> 9pm Sunday, Saturday" as well? Of course I will create another issue.

**Comment by tomasrudh** [comment]
I understand your use case. However, I have not had this request from anyone else, nor do I need it myself. So I am sorry to say I will deny your request. But thank you so much for reaching out!

**Comment by margani** [comment]
Sure, no worries.
